Only wrap as much code with System Lambda as necessary
nasirov/proxy-server pull request #1
Opened 2020-08-24 22:00 UTC by stefanbirkner

This makes it clear which part of the code needs the environment
variables.

2020-08-25 09:03 UTC, nasirov requested changes
Minor code style remarks

2020-08-30 10:15 UTC, stefanbirkner commented on src/test/java/nasirov/yv/proxy/server/task/SocketServerThreadTest.java
> +
Done.

2020-08-30 10:15 UTC, stefanbirkner commented on src/test/java/nasirov/yv/proxy/server/task/SocketServerThreadTest.java
> +
Done

2020-08-30 10:15 UTC, stefanbirkner commented on src/test/java/nasirov/yv/proxy/server/task/SocketServerThreadTest.java
> +
Done

2020-08-30 10:37 UTC, nasirov approved these changes

2020-08-30 10:39 UTC, merged